### ISSUE TITLE
Plan GSOC participation for 2018

### ISSUE THREAD

**Issue by caniszczyk** [cncf/soc#22]

**Comment by caniszczyk** [comment]
cc: @idvoretskyi we will put this in queue for Q2 2018

**Comment by idvoretskyi** [comment]
@caniszczyk +1

**Comment by nikhita** [comment]
Related https://github.com/cncf/soc/pull/23

**Comment by Gouthamve** [comment]
@caniszczyk @idvoretskyi I am a Prometheus contributor and got started only because of GSoC. I would love to see GSoC happen again, but given the deadline is in a week, I was wondering if I could be of any assistance.

I sent out a call for ideas for GSoC in the Prometheus mailing-list and already have a list of ideas here: https://groups.google.com/forum/#!topic/prometheus-developers/EoWEOEkWXNc

**Comment by idvoretskyi** [comment]
@Gouthamve perfect, thank you.

**Comment by caniszczyk** [comment]
Thanks so much @Gouthamve, the best way you can help is coming up with project ideas and mentor any of them within the Prometheus community!

**Comment by caniszczyk** [comment]
@Gouthamve can you do a PR and update the Prometheus section with project ideas?

I started with one carry over idea: https://github.com/cncf/soc/blob/master/README.md#prometheus

**Comment by sttts** [comment]
Has there been a call-out for kube? If not, we should send out a link to a Google Doc again. Worked fine last year.

**Comment by nikhita** [comment]
> Has there been a call-out for kube?

https://groups.google.com/forum/#!topic/kubernetes-wg-contribex/5GPCKMvzylw

**Comment by Skywalker97** [comment]
Hi
I want to work on one of your projects in GSOC 2018 but I am not a contributor on cncf. Will this hamper my chances of getting selected? Do existing contributors get any special preferance?

**Comment by SeanPSnyder** [comment]
To piggyback on @Skywalker97, how much could a month of contributions do to really move the needle? Does CNCF reach out to professors or references, especially for those with limited public code bases? Is there some sort of coding challenge mechanism? Should we focus on current projects and start preparing/refining good examples of our work or what's the advice for students with a heavy academic/start-up workload (but a very nice GSOC-sized gap in the summer)?

**Comment by nikhita** [comment]
@Skywalker97 

> I want to work on one of your projects in GSOC 2018 but I am not a contributor on cncf. 

It's awesome you want to work on a CNCF project, welcome! :tada: 

You don't need to be an existing contributor to any CNCF project. You can start now as well! :)

> Will this hamper my chances of getting selected?

Absolutely not.

> Do existing contributors get any special preference?

There is **no** special preference for anyone (that includes existing contributors). Selection in GSoC depends on multiple factors - how you communicate, how well you are able to grasp the code, your initial contributions (more on this later), your application, etc. There is no single metric or formula for selection.

For GSoC, one of the things we do is to assign a task/issue to you and ask you to solve it. We are more than happy to answer questions and provide mentorship for solving these tasks. Your contributions (even if your patch is not merged) to such tasks is a huge plus to your application.

This does not necessarily imply that existing contributors are favoured since selection is dependent on several criteria.

There is still time so I would suggest you to start reaching out to the mentor/project you are interested in and ask for an issue or task to begin with. If you need any help, feel free to ping me!

**Comment by nikhita** [comment]
@SeanPSnyder 
> how much could a month of contributions do to really move the needle? 

Like I mentioned above to @Skywalker97, (a month of) contributions are a huge plus but not a guarantee for selection.

> Does CNCF reach out to professors or references, especially for those with limited public code bases? 

No, we don't require references (at least for Kubernetes, though I am sure other CNCF projects would follow the same principle). We look at multiple factors and your initial contributions gives us a good idea about how you can work with the project during the GSoC duration.

> Is there some sort of coding challenge mechanism? 

We give you a task to work on but I wouldn't call it a "coding challenge". It's a task to get your feet wet and to make you feel comfortable with the project. Moreover, we provide mentorship for these tasks.

> Should we focus on current projects

By current projects, do you mean the projects listed in the README? Then yes, please choose a project and reach out to the mentor.

> start preparing/refining good examples of our work

We don't generally look into your previous projects and use it as a metric for selection. How you contribute to _our_ project is what matters since you will be working on it during GSoC. Having said that, if you have had previous experiences in the technologies that the project needs, make sure that you let us know! :)

> what's the advice for students with a heavy academic/start-up workload (but a very nice GSOC-sized gap in the summer)?

I understand that academic workload can be overbearing (I am a student myself!) but if you could spend a few hours on the task/project/application each week, that would be great.

Let us know if you have other commitments during the application period and we'll keep it in mind.  :+1: 
To be clear, this will not reflect negatively on your application. Communication is a good thing! :)

**Comment by nikhita** [comment]
I guess this can be closed now, given that the "planning" phase is done. Please reopen if you feel otherwise. :)
