### ISSUE TITLE
Add Kubernetes workload benchmarker idea

### ISSUE THREAD

**Issue by mozhuli** [cncf/soc#34]
I am a Gopher and a student from SEL laboratory of Zhejiang University, I am digging into kubernetes and SDN when pursuing my master degree, and contribute some code in cri-containerd, stackube and ovn-kubernetes projects.

We have a proposal for kubernetes workload benchmarker which was  inspired from [PerfKitBenchmarker](https://github.com/GoogleCloudPlatform/PerfKitBenchmarker) project which focuses on VM, and this proposal will focuses on the capability of kubernetes by providing wrappers and workload definitions around popular benchmark tools.

This is our [proposal](https://docs.google.com/document/d/1hYOzX8jBHceuXgDVzlasveMqetpKtnq433aNMj1_x0o/edit?usp=sharing). And I have already created a repository [capstan](https://github.com/ZJU-SEL/capstan) and have completed the development of the basic testing framework.

We plan to push it into kubernetes-incubator initially, but  we found that kubernetes-incubator has been frozen temporarily.  So we want to put it as a idea of gsoc and we can achieve it with high quality under the guide of mentor which has talked about with @idvoretskyi

Here's some question:

1.  The idea can not come from the exited repository under CNCF?

2.  We find the mentor of the idea who interested in it by ourselves or cncf will help it? 

3.  Only one student accomplish one idea?

/cc @caniszczyk @idvoretskyi

**Comment by idvoretskyi** [comment]
cc @nikhita

**Comment by nikhita** [comment]
I have a few questions and points here.

> I am a Gopher and a student from SEL laboratory of Zhejiang University, I am digging into kubernetes and SDN when pursuing my master degree, and contribute some code in cri-containerd, stackube and ovn-kubernetes projects.

Firstly, this is great to hear and welcome to the community! 🎉 

> This is our proposal.

I would like to stress on the word _our_ here. From the [official Google Summer of Code FAQ](https://developers.google.com/open-source/gsoc/faq),

> Can a group submit a proposal together to work on a single project?
No, only an individual may work on a given project. 

From what you wrote, it looks like the proposal has been a combined effort of a group of students. This is not allowed for Google Summer of Code. Writing the proposal **and** doing the GSoC project are supposed to be done individually.

> And I have already created a repository capstan and have completed the development of the basic testing framework.

From the [official Google Summer of Code rules](https://summerofcode.withgoogle.com/rules/) Section 6.4 (d),

> If a Project Proposal is for a Project that the Student is already working on, the Student must note this in the Project Proposal. Any work done on the Project prior to acceptance of the Project Proposal will not be considered for Evaluations.

I know you didn't ask this but I just want to make it clear that any work that you have accomplished on the project prior to acceptance will not be counted for evaluations.

>  We plan to push it into kubernetes-incubator initially, but we found that kubernetes-incubator has been frozen temporarily. So we want to put it as a idea of gsoc and we can achieve it with high quality under the guide of mentor 

If this needs to be accepted as a gsoc project, it can either be under two categories:

1. **Under the Kubernetes project in CNCF** - In this case, it would be beneficial if this feature/code could be incorporated into upstream (in any of the projects, not just the `kubernetes/kubernetes` repository). Since kubernetes-incubator is frozen temporarily, I would suggest you to reach out (Slack is a good idea) to the relevant SIG and talk about interest in a project like this. 

If there is interest + people are willing to mentor + proposal is accepted, this can be accepted as a gsoc project.

@idvoretskyi would sig-architecture be a good choice in this case?

2. **Under CNCF** - If there seems to be not much interest from the Kubernetes side, maybe CNCF could consider this as a project under it? Not sure if this is possible. @caniszczyk @idvoretskyi would be the right people to answer this.

Now to answer your specific questions:

> 1. The idea can not come from the exited repository under CNCF?

I am not entirely sure what you mean here.

Do you mean to ask if it is necessary that the project idea needs to be an idea from the published ideas list? If so, the answer is no. You are free to propose your own ideas.

If you mean to ask if it is necessary that the project idea needs to be an idea from the existing repositories/projects under CNCF, @caniszczyk or @idvoretskyi can answer it.

> 2. We find the mentor of the idea who interested in it by ourselves or cncf will help it?

I would be more than happy to help you find a mentor. :)

But please keep in mind that this would be an individual project (stress on the word _ourselves_ in what you wrote) and there needs to be an interest for this project.

> 3. Only one student accomplish one idea?

All the work needs to be done individually.

However, there can be student projects which are interlinked. If there is more than one student who is interested in accomplishing this project and if there is more than one mentor available for this project, then both of them could work individually on the same project but on different components/features.

So from what I see, you should find out:

1. If there is an interest in incorporating this upstream by reaching out to the relevant SIG. If yes, are there people willing to mentor you? (I can help find mentors).

2. If there seems to be less interest in incorporating it upstream, can it be a repository/project under the cncf org directly?  @caniszczyk @idvoretskyi 

3. If there is more than one of you who is interested in this, can you divide the project in such a way that all of you could work in parallel? Note: we will still need mentors for each of you and each of you needs to write a separate proposal.


Lastly, this seems very exciting and hopefully, we can make it work. :)

**Comment by mozhuli** [comment]
@nikhita Thanks for your detailed answer! Our main purpose is to find a way to introduce the idea and collaborate to accomplish it with community, we have done a few works with the idea. The proposal is quite a big, most work is done by myself currently, I will continue to contact with the relevant SIGs.  And I will try to divide the project into different components. 

Hope for your further advices! @idvoretskyi @caniszczyk
