### ISSUE TITLE
Plan GSoC participation for 2019

### ISSUE THREAD

**Issue by idvoretskyi** [cncf/soc#50]
[CNCF has successfully participated in GSoC 2018](https://www.cncf.io/blog/2018/09/04/cncfs-full-gsoc-roster-passes-summer-evaluations/), having [7 of 7 projects accepted and passed the final evaluations](https://summerofcode.withgoogle.com/organizations/6453865516367872/#projects).

Now it's time to start planning the GSoC 2019 participation.

**Comment by bargemb** [comment]
Hi Ihor,
    I am a graduate student of San José State University and interested in participating for GSoC 2019. I have background on Kubernetes and started Kelsey's "Kubernetes The Hard Way" to revise knowledge. I would appreciate any guidance on how to proceed with this.
    To begin with, I joined cncf slack channel.

Regards,
Mayur

**Comment by nikhita** [comment]
@bargemb Welcome! :wave: 

If you are interested in Kubernetes, please join the Kubernetes slack: http://slack.k8s.io/.

In Kubernetes, we have multiple SIGs (Special Interest Groups) which focus on particular "parts" in the whole Kubernetes ecosystem. You can find the list of SIGs [here](https://github.com/kubernetes/community/blob/master/sig-list.md). I'd suggest you to pick up a SIG and start getting to know their codebase better.

There is also a "Meet Our Contributors" session held by @parispittman where you can ask questions about getting started, etc to the existing contributors...and the session for this month happens to be today! :tada: 

You can find more details about today's session [here](https://groups.google.com/forum/#!topic/kubernetes-dev/SEq9wLFaUrY). I'd strongly suggest to attend that and ask all the questions you have. :)

**Comment by nikhita** [comment]
@idvoretskyi the blog post is cool! :ok_hand:

**Comment by idvoretskyi** [comment]
@bargemb welcome! Please, join us at the Kubernetes community for the details on getting started with the Kubernetes contributions, and I'll keep this thread updated on the GSoC-specific questions (more details soon). 

@nikhita thank you, you did a lot for CNCF's GSoC program in 2018 :)

**Comment by bargemb** [comment]
Thank you @idvoretskyi and @nikhita for your inputs. Looking forward to hearing more from you on GSoC 2019.

**Comment by pandyamarut** [comment]
@nikhita Where are Cncf projects?

**Comment by nikhita** [comment]
@pandyamarut You can find details about all CNCF projects on the website: https://www.cncf.io/projects/

**Comment by Abhik1998** [comment]
Hii I am a cloud computing solutions enthusiast and want to learn more of Kubernetes and cloud

**Comment by Abhik1998** [comment]
I am much eager to participate in Gsoc 2019

**Comment by Abhik1998** [comment]
@nikhita  and @idvoretskyi 
I am solving issues upon Kubernetes project what should be my next move?

**Comment by sourabh1031** [comment]
Hello @idvoretskyi @nikhita I am Sourabh , greatly interested to be a part of CNCF family. I am looking to apply in upcoming GSoC 2019 under your org.Please provide me a starter guide , including good first issues which i need to solve to get my hands dirty with the codebase, communication channels, prerequisites that i must have to get started (like how much knowledge of docker , k8s or golang).

**Comment by nikhita** [comment]
For those interested in Kubernetes -- I've received some emails and DMs regarding gsoc recently. The best way to ask questions or discuss about this is in the #gsoc-apps channel on the Kubernetes slack (you can get an invite for it [here](http://slack.k8s.io/)).

Also, we will start with the gsoc process soon and I'll give an update when we do so. For now, please stick to asking questions on the channel. Thanks! :)

**Comment by angadsharma1016** [comment]
Hi. I would like to contribute to this project for GSOC 2019. I am familiar with golang, docker and docker-swarm, node.js, SQL, mongoDB, neo4j and electron.js  Where can i start?

**Comment by nikhita** [comment]
@angadsharma1016 Please follow the links mentioned in the comments above and check out the projects in the README. Depending on the projects that you are interested in, reach out to the mentors (preferably in a public channel) and let them know that you are interested.

I recently wrote some points about how to get started in the #gsoc-apps channel in Kubernetes slack. Pasting this here so that it reaches more people (some of this is Kubernetes-specific):

--- 

If you are a student, now would be a good time to reach out to the mentors on the respective SIG channel and let them know that you are interested in participating in GSoC. Make sure to introduce yourself and let them know what languages, etc you are already familiar with.

Also add some information about the background reading that you have done for the project idea. It is easier to help someone when you know they have done some research from their side. :) And then ask your mentors if they could point you to a beginner friendly issue that you could get started with.

For instance, in the case of https://github.com/cncf/soc#add-support-for-custom-resource-definitions-to-the-dashboard - a good background study would be to read about what a Custom Resource Definition (CRD) is, what Third Party Resources (TPRs) were and how support for TPRs was added to the dashboard (there are links to it in the issue). You can also read more about how to contribute to dashboard in general and look for good-first-issues in the repo.

If you have questions while doing a background study for any of the project ideas, feel free to ping the mentors. Remember that there are no stupid questions. :)

A few more points:

- Please wait _at least_ 24 hours before pinging your mentors again if you don't get a response. They might be busy or in a different timezone. If you don't get a response at all for Kubernetes, ping me.

- For any questions related to GSoC, please use a public channel instead of DMs wherever possible. We are an open source community and should strive to be as open as possible. :)

**Comment by Helinia** [comment]
@nikhita Hi there, I am interested in contributing. However, I find that the link to Kubernetes slack is unavailable. Can you provide a valid link, please? I appreciate your help.

**Comment by nikhita** [comment]
@Helinia Good question! The Kubernetes Slack inviter was shut down recently due to spam attacks. We are working on getting that fixed in the next few days.

Till then, I'd suggest to look at the [existing project ideas](https://github.com/cncf/soc#kubernetes), choose the one that sounds interesting to you and introduce yourself on the issue mentioned in the project idea (make sure to ping the mentors and let them know that you are asking this here because Slack is down).

Then ask them for a `good first issue` or if you find an issue on the repo that you'd like to work on, feel free to add a comment there that you'd like to work on it. :)

I'd also suggest to track https://github.com/kubernetes/community/issues/3247, which will have updates about when Slack will be back up.

Apologies for all the trouble, @Helinia! In case you have any questions, feel free to ping me here on this issue again.

**Comment by sourabhdeshmukh** [comment]
Hello everyone,
I'm a last year B.Tech student and looking forward to participate in Gsoc'19.
I would sincerely seek your help in contributing to projects.
Thank you.

**Comment by mrkarna** [comment]
Hi everyone, Can any one share the GSoC project ideas list link?

**Comment by caniszczyk** [comment]
@mrkarna https://github.com/cncf/soc#project-ideas

**Comment by justinzhf** [comment]
@idvoretskyi  hi! I am a graduate student of Nanjing University of Aeronautics and Astronautics. My major is data mining, to be exact, research on anomaly detection of complex system. I have finished a paper about power system anomaly detection. I am interested in this idea of GSoC 2019(https://github.com/cncf/soc/blob/master/README.md#falco-integration-with-aiml-platforms). I really want to do something about this idea, could you tell me how can I get started?

**Comment by yas1nth** [comment]
@nikhita @idvoretskyi
Hi there,
I am B.E undergraduate from chaitanya bharati institute of technology. My major contribution is fro home automation using cloud computing and IOT.I am very much interested for GSOC 2019

**Comment by idvoretskyi** [comment]
Done.

Publicly announced at https://www.cncf.io/blog/2019/08/23/cncf-joins-google-summer-of-code-2019-with-17-interns-projects-for-containerd-coredns-kubernetes-opa-prometheus-rook-and-more/
